### ISSUE TITLE
nltk issue may cause error on your library(MACOSX)

### ISSUE THREAD

**Issue by Amirlashkar** [roshan-research/hazm#291]
i already had both nltk and hazm installed; for using each of them had same error; error below is for hazm usage:

['Credit Risk', 'Supply Risk']
Traceback (most recent call last):
  File "/Users/albk/Documents/Code/Learning_Projects/NLP/hazm_.py", line 1, in <module>
    from hazm import *
  File "/Users/albk/anaconda3/lib/python3.10/site-packages/hazm/__init__.py", line 20, in <module>
    from hazm.pos_tagger import POSTagger
  File "/Users/albk/anaconda3/lib/python3.10/site-packages/hazm/pos_tagger.py", line 10, in <module>
    from nltk.tag import stanford
  File "/Users/albk/anaconda3/lib/python3.10/site-packages/nltk/__init__.py", line 138, in <module>
    from nltk.text import *
  File "/Users/albk/anaconda3/lib/python3.10/site-packages/nltk/text.py", line 29, in <module>
    from nltk.tokenize import sent_tokenize
  File "/Users/albk/anaconda3/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 65, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "/Users/albk/anaconda3/lib/python3.10/site-packages/nltk/tokenize/casual.py", line 215, in <module>
    HANG_RE = regex.compile(r"([^a-zA-Z0-9])\1{3,}")
AttributeError: module 'regex' has no attribute 'compile'

i'm on mac and it seems thats relevent to error; 

solution:
just go to "nltk/tokenize/casual.py" file and replace all "regex" things with "re" to make nltk use built-in regex !!!

**Comment by sir-kokabi** [comment]
سلام.
از کدوم نسخهٔ هضم و nltk استفاده می‌کنید؟

**Comment by Amirlashkar** [comment]
> سلام. از کدوم نسخهٔ هضم و nltk استفاده می‌کنید؟

Name: hazm
Version: 0.9.3

Name: nltk
Version: 3.8.1

**Comment by sir-kokabi** [comment]
لطفاً یک نمونه کد کوتاه (ترجیحاً روی colab) که این خطا رو تولید می‌کنه به اشتراک بگذارید.

**Comment by imani** [comment]
> > سلام. از کدوم نسخهٔ هضم و nltk استفاده می‌کنید؟
> 
> Name: hazm Version: 0.9.3
> 
> Name: nltk Version: 3.8.1

نسخه regex تون رو چک کنید، روی نسخه 2.5.129 چک کردم خطایی نداشتم.
